export const GET_LIST_ARTICLE_SUCCESS = "GET_LIST_ARTICLE_SUCCESS";
export const GET_LIST_ARTICLE_FAILED = "GET_LIST_ARTICLE_FAILED";

export const GET_LIST_VIEW_ARTICLE_SUCCESS = "GET_LIST_VIEW_ARTICLE_SUCCESS";
export const GET_LIST_VIEW_ARTICLE_FAILED = "GET_LIST_VIEW_ARTICLE_FAILED";

export const GET_DETAIL_ARTICLE_BY_ID_SUCCESS =
  "GET_DETAIL_ARTICLE_BY_ID_SUCCESS";
export const GET_DETAIL_ARTICLE_BY_ID_FAILED =
  "GET_DETAIL_ARTICLE_BY_ID_FAILED";
