export const GET_DEAL_BY_ID_SUCCESS = "GET_DEAL_BY_ID_SUCCESS";
export const GET_DEAL_BY_ID_FAILD = "GET_DEAL_BY_ID_FAILD";

export const GET_CURRENT_DEAL_SUCCESS = "GET_CURRENT_DEAL_SUCCESS";
export const GET_CURRENT_DEAL_FAILD = "GET_CURRENT_DEAL_FAILD";

export const GET_CURRENT_DEAL_DONE_SUCCESS = "GET_CURRENT_DEAL_DONE_SUCCESS";
export const GET_CURRENT_DEAL_DONE_FAIL = "GET_CURRENT_DEAL_DONE_FAIL";

export const GET_CURRENT_DEAL_CANCEL_SUCCESS = "GET_CURRENT_DEAL_CANCEL_SUCCESS";
export const GET_CURRENT_DEAL_CANCEL_FAIL = "GET_CURRENT_DEAL_CANCEL_FAIL";

export const GET_DETAIL_DEAL_SUCCESS = "GET_DETAIL_DEAL_SUCCESS";
export const GET_DETAIL_DEAL_FAIL = "GET_DETAIL_DEAL_FAIL";

export const UPDATE_DEAL_ACCEPT_SUCCESS = "UPDATE_DEAL_ACCEPT_SUCCESS";
export const UPDATE_DEAL_ACCEPT_FAIL = "UPDATE_DEAL_ACCEPT_FAIL";

export const UPDATE_DEAL_REJECT_SUCCESS = "UPDATE_DEAL_REJECT_SUCCESS";
export const UPDATE_DEAL_REJECT_FAIL = "UPDATE_DEAL_REJECT_FAIL";
  
export const CREATE_DEAL_SUCCESS = "CREATE_DEAL_SUCCESS";
export const CREATE_DEAL_FAIL = "CREATE_DEAL_FAIL";
