export const GET_DEAL_BY_ID_SUCCESS = "GET_DEAL_BY_ID_SUCCESS";
export const GET_DEAL_BY_ID_FAILD = "GET_DEAL_BY_ID_FAILD";

export const GET_CURRENT_DEAL_SUCCESS = "GET_CURRENT_DEAL_SUCCESS";
export const GET_CURRENT_DEAL_FAILD = "GET_CURRENT_DEAL_FAILD";

export const GET_CURRENT_DEAL_DONE_SUCCESS = "GET_CURRENT_DEAL_DONE_SUCCESS";
export const GET_CURRENT_DEAL_DONE_FAIL = "GET_CURRENT_DEAL_DONE_FAIL";

export const GET_CURRENT_DEAL_CANCEL_SUCCESS = "GET_CURRENT_DEAL_CANCEL_SUCCESS";
export const GET_CURRENT_DEAL_CANCEL_FAIL = "GET_CURRENT_DEAL_CANCEL_FAIL";