export const GET_FREE_TIME_LIST_SUCCESS = "GET_FREE_TIME_LIST_SUCCESS";
export const GET_FREE_TIME_LIST_FAILED = "GET_FREE_TIME_LIST_FAILED";
export const GET_FREE_TIME_LIST_OF_ORGANIZATION_SUCCESS = "GET_FREE_TIME_LIST_OF_ORGANIZATION_SUCCESS";
export const GET_FREE_TIME_LIST_OF_ORGANIZATION_FAIL = "GET_FREE_TIME_LIST_OF_ORGANIZATION_FAIL";
export const GET_FREE_TIME_DETAIL_OF_ORGANIZATION_SUCCESS = "GET_FREE_TIME_DETAIL_OF_ORGANIZATION_SUCCESS";
export const GET_FREE_TIME_DETAIL_OF_ORGANIZATION_FAIL = "GET_FREE_TIME_DETAIL_OF_ORGANIZATION_FAIL";
export const GET_ALL_FREE_TIME_LIST_SUCCESS = "GET_ALL_FREE_TIME_LIST_SUCCESS";
export const GET_ALL_FREE_TIME_LIST_FAILED = "GET_ALL_FREE_TIME_LIST_FAILED";
