export const GET_LIST_INTRODUCE_SUCCESS = "GET_LIST_INTRODUCE_SUCCESS";
export const GET_LIST_INTRODUCE_FAILED = "GET_LIST_INTRODUCE_FAILED";

export const GET_LIST_INTRODUCE_BY_ROUND_SUCCESS = "GET_LIST_INTRODUCE_BY_ROUND_SUCCESS";
export const GET_LIST_INTRODUCE_BY_ROUND_FAILED = "GET_LIST_INTRODUCE_BY_ROUND_FAILED";

export const GET_LIST_DOCUMENT_BY_ROUND_SUCCESS = "GET_LIST_DOCUMENT_BY_ROUND_SUCCESS";
export const GET_LIST_DOCUMENT_BY_ROUND_FAILED = "GET_LIST_DOCUMENT_BY_ROUND_FAILED";


