export const GET_VERIFICATION_CODE_SUCCESS = "GET_VERIFICATION_CODE_SUCCESS";

export const GET_LIST_INDUSTRY_SUCCESS = "GET_LIST_INDUSTRY_SUCCESS";
export const GET_LIST_INDUSTRY_FAIL = "GET_LIST_INDUSTRY_FAIL";

export const GET_LIST_STAGE_SUCCESS = "GET_LIST_STAGE_SUCCESS";
export const GET_LIST_STAGE_FAIL = "GET_LIST_STAGE_FAIL";

export const GET_LIST_PROVINCE_SUCCESS = "GET_LIST_PROVINCE_SUCCESS";
export const GET_LIST_PROVINCE_FAIL = "GET_LIST_PROVINCE_FAIL";

export const GET_LIST_REGION_SUCCESS = "GET_LIST_REGION_SUCCESS";
export const GET_LIST_REGION_FAILED = "GET_LIST_REGION_FAILED";

export const GET_LIST_INVESTOR_TYPE_SUCCESS = "GET_LIST_INVESTOR_TYPE_SUCCESS";
export const GET_LIST_INVESTOR_TYPE_FAILED = "GET_LIST_INVESTOR_TYPE_FAILED";

export const CREATE_BASIC_INFORMATION_SUCCESS =
  "CREATE_BASIC_INFORMATION_SUCCESS";
export const CREATE_BASIC_INFORMATION_FAIL = "CREATE_BASIC_INFORMATION_FAIL";

export const CREATE_IAT_ORGANIZATION_SUCCESS =
  "CREATE_IAT_ORGANIZATION_SUCCESS";
export const CREATE_IAT_ORGANIZATION_FAIL = "CREATE_IAT_ORGANIZATION_FAIL";

export const CREATE_ORGANIZATION_INDUSTRY_SUCCESS =
  "CREATE_ORGANIZATION_INDUSTRY_SUCCESS";
export const CREATE_ORGANIZATION_INDUSTRY_FAIL =
  "CREATE_ORGANIZATION_INDUSTRY_FAIL";

export const CREATE_ORGANIZATION_PROVINCCE_SUCCESS =
  "CREATE_ORGANIZATION_PROVINCCE_SUCCESS ";
export const CREATE_ORGANIZATION_PROVINCCE_FAIL =
  "CREATE_ORGANIZATION_PROVINCCE_FAIL";

export const CREATE_ORGANIZATION_STAGE_SUCCESS =
  "CREATE_ORGANIZATION_STAGE_SUCCESS";
export const CREATE_ORGANIZATION_STAGE_FAIL = "CREATE_ORGANIZATION_STAGE_FAIL";
