export const GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_FAILED";
export const GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_FAILED";
export const GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_FAILED";
export const GET_ALL_LIST_ROUND_ACTIVE_SUCCESS =
  "GET_ALL_LIST_ROUND_ACTIVE_SUCCESS";
export const GET_ALL_LIST_ROUND_ACCTIVE_FAILED =
  "GET_ALL_LIST_ROUND_ACCTIVE_FAILED";
// v2
export const GET_LIST_ROUND_BY_ID_INVESTOR_SUCCESS =
  "GET_LIST_ROUND_BY_ID_INVESTOR_SUCCESS";
export const GET_LIST_ROUND_BY_ID_INVESTOR_FAILED =
  "GET_LIST_ROUND_BY_ID_INVESTOR_FAILED";
export const GET_LIST_ROUND_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_BY_ID_ORGANIZATION_FAILED";
export const GET_LIST_ALL_ROUND_SUCCESS = "GET_LIST_ALL_ROUND_SUCCESS";
export const GET_LIST_ALL_ROUND_FAILED = "GET_LIST_ALL_ROUND_FAILED";
