export const GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_ACTIVE_BY_ID_ORGANIZATION_FAILED";
export const GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_PASS_BY_ID_ORGANIZATION_FAILED";
export const GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_PENDING_BY_ID_ORGANIZATION_FAILED";
export const GET_ALL_LIST_ROUND_ACTIVE_SUCCESS =
  "GET_ALL_LIST_ROUND_ACTIVE_SUCCESS";
export const GET_ALL_LIST_ROUND_ACCTIVE_FAILED =
  "GET_ALL_LIST_ROUND_ACCTIVE_FAILED";
// v2
export const GET_LIST_ROUND_BY_ID_INVESTOR_SUCCESS =
  "GET_LIST_ROUND_BY_ID_INVESTOR_SUCCESS";
export const GET_LIST_ROUND_BY_ID_INVESTOR_FAILED =
  "GET_LIST_ROUND_BY_ID_INVESTOR_FAILED";
export const GET_LIST_ROUND_BY_ID_ORGANIZATION_SUCCESS =
  "GET_LIST_ROUND_BY_ID_ORGANIZATION_SUCCESS";
export const GET_LIST_ROUND_BY_ID_ORGANIZATION_FAILED =
  "GET_LIST_ROUND_BY_ID_ORGANIZATION_FAILED";


  export const GET_LIST_QUESTION_AND_ANSWER_SUCCESS =
  "GET_LIST_QUESTION_AND_ANSWER_SUCCESS";
export const GET_LIST_QUESTION_AND_ANSWER_FAIL =
  "GET_LIST_QUESTION_AND_ANSWER_FAIL";

  
  export const CREATE_QUESTION_SUCCESS =
  "CREATE_QUESTION_SUCCESS";
export const CREATE_QUESTION_FAIL =
  "CREATE_QUESTION_FAIL";

  export const CREATE_ANSWER_SUCCESS =
  "CREATE_ANSWER_SUCCESS";
export const CREATE_ANSWER_FAIL =
  "CREATE_ANSWER_FAIL";

  export const GET_ROUND_AND_ORGANIZATION_SUCCESS =
  "GET_ROUND_AND_ORGANIZATION_SUCCESS";
export const GET_ROUND_AND_ORGANIZATION_FAIL =
  "GET_ROUND_AND_ORGANIZATION_FAIL";

  export const GET_LIST_DEAL_BY_ROUND_SUCCESS =
  "GET_LIST_DEAL_BY_ROUND_SUCCESS";
export const GET_LIST_DEAL_BY_ROUND_FAIL =
  "GET_LIST_DEAL_BY_ROUND_FAIL";

export const GET_LIST_ALL_ROUND_SUCCESS = "GET_LIST_ALL_ROUND_SUCCESS";
export const GET_LIST_ALL_ROUND_FAILED = "GET_LIST_ALL_ROUND_FAILED";

